using System.Net;
using System.Net.Http.Json;
using UrlShortener.Api;

namespace UrlShortener.Tests;

public class LinkApiTests : TestServerFixture
{

    [Fact] public async Task Empty_list_is_empty() { var response = await Client.GetAsync("/api/links"); Assert.Equal(HttpStatusCode.OK, response.StatusCode); Assert.Equal("[]", await response.Content.ReadAsStringAsync()); }
    [Theory] [InlineData("https://example.com")] [InlineData("http://example.com")] public async Task Create_returns_201_and_short_url(string url) { var response = await Client.PostAsJsonAsync("/api/links", new { url }); Assert.Equal(HttpStatusCode.Created, response.StatusCode); var body = await response.Content.ReadFromJsonAsync<LinkResponse>(); Assert.NotNull(body); Assert.Contains(body!.Code, body.ShortUrl); }
    [Fact] public async Task Sequential_creates_have_unique_codes() { var one = await (await Client.PostAsJsonAsync("/api/links", new { url = "https://one.example" })).Content.ReadFromJsonAsync<LinkResponse>(); var two = await (await Client.PostAsJsonAsync("/api/links", new { url = "https://two.example" })).Content.ReadFromJsonAsync<LinkResponse>(); Assert.NotEqual(one!.Code, two!.Code); }
    [Theory] [InlineData("")] [InlineData("not-a-url")] [InlineData("ftp://x.com")] public async Task Invalid_create_returns_400(string url) => Assert.Equal(HttpStatusCode.BadRequest, (await Client.PostAsJsonAsync("/api/links", new { url })).StatusCode);
    [Fact] public async Task Empty_or_malformed_or_null_body_returns_400() { Assert.Equal(HttpStatusCode.BadRequest, (await Client.PostAsync("/api/links", new StringContent("{}", System.Text.Encoding.UTF8, "application/json"))).StatusCode); Assert.Equal(HttpStatusCode.BadRequest, (await Client.PostAsync("/api/links", new StringContent("{", System.Text.Encoding.UTF8, "application/json"))).StatusCode); Assert.Equal(HttpStatusCode.BadRequest, (await Client.PostAsync("/api/links", new StringContent("{\"url\":null}", System.Text.Encoding.UTF8, "application/json"))).StatusCode); }
    [Fact] public async Task Redirect_and_click_count_work() { var created = await Client.PostAsJsonAsync("/api/links", new { url = "https://example.com/a" }); var body = await created.Content.ReadFromJsonAsync<LinkResponse>(); var redirect = await Client.GetAsync("/" + body!.Code); Assert.Equal(HttpStatusCode.Redirect, redirect.StatusCode); Assert.Equal("https://example.com/a", redirect.Headers.Location!.ToString()); var list = await Client.GetFromJsonAsync<LinkResponse[]>("/api/links"); Assert.Equal(1, list![0].ClickCount); }
    [Fact] public async Task Three_redirects_count_as_three_and_list_has_contract_fields() { var body = await (await Client.PostAsJsonAsync("/api/links", new { url = "https://example.com/clicks" })).Content.ReadFromJsonAsync<LinkResponse>(); for (var i = 0; i < 3; i++) await Client.GetAsync("/" + body!.Code); var list = await Client.GetFromJsonAsync<LinkResponse[]>("/api/links"); Assert.Equal(3, list![0].ClickCount); var json = await (await Client.GetAsync("/api/links")).Content.ReadAsStringAsync(); Assert.Contains("code", json); Assert.Contains("originalUrl", json); Assert.Contains("shortUrl", json); Assert.Contains("clickCount", json); }
    [Fact] public async Task Numeric_code_redirects() { var body = await (await Client.PostAsJsonAsync("/api/links", new { url = "https://example.com/numeric" })).Content.ReadFromJsonAsync<LinkResponse>(); Assert.Equal("1", body!.Code); Assert.Equal(HttpStatusCode.Redirect, (await Client.GetAsync("/1")).StatusCode); }
    [Fact] public async Task Unknown_and_invalid_codes_404() { Assert.Equal(HttpStatusCode.NotFound, (await Client.GetAsync("/999999")).StatusCode); Assert.Equal(HttpStatusCode.NotFound, (await Client.GetAsync("/abc!@#")).StatusCode); }
    [Fact] public async Task Root_serves_index_and_list_is_newest_first() { Assert.Equal(HttpStatusCode.OK, (await Client.GetAsync("/")).StatusCode); await Client.PostAsJsonAsync("/api/links", new { url = "https://one.example" }); await Client.PostAsJsonAsync("/api/links", new { url = "https://two.example" }); var list = await Client.GetFromJsonAsync<LinkResponse[]>("/api/links"); Assert.Equal("https://two.example", list![0].OriginalUrl); Assert.Equal("https://one.example", list[1].OriginalUrl); }
}
